http:
  host: 0.0.0.0
  port: 34567
database:
  host: megrez-postgres
  port: 5432
  username: XshengTechMEGREZ
  password: XshengTechMEGREZ
  database: XshengTechMEGREZ
redis:
  host: megrez-redis
  port: 6379
system:
  verify: false
  mount_dir: /path/to/mount
