http:
  host: 0.0.0.0
  port: 34567
database:
  host: megrez-postgres
  port: 5432
  username: XshengTechMEGREZ
  password: XshengTechMEGREZ
  database: XshengTechMEGREZ
redis:
  host: megrez-redis
  port: 6379
smtp:
  host:
  port:
  user:
  password:
  ssl: false
system:
  base_url: 
  verify: false
  mount_dir: 
